### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by sunnyHelen** [JonDoe-297/cross-view#3]
Hi, thanks a lot for sharing your interesting and great work.
I ran test.py following your instructions but got results like this.
![image](https://user-images.githubusercontent.com/28101548/126326990-81684dee-4f64-4e31-8c59-f54b8c417e26.png)
There are no results of vehicles. I noticed there is an args item "type", but it seems to only work for saving directory. Is there anything I got wrong?

**Comment by JonDoe-297** [comment]
Thanks for following our work. Since some datasets provide the annotations for road layout or vehicle occupancies only, we generate roads and vehicles separately, even Argoverse dataset.  Maybe you are using a road model, you should just replace it with a vehicle.

This is my test parameter for the vehicle model：
```
python test.py 
--type dynamic 
--model_path <path to the model directory. e.g. KITTI 3D Object> 
--image_path <path to the image directory>  
-out_dir ./output/kitti/3Dobject
```
